[package]
name = "herald"
version = "0.1.0"
authors = ["Alex Studer <alex@studer.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
toml = "0.5.3"